"""ddsummary tables

Revision ID: 446aeac2a500
Revises: 5c0f7774b727
Create Date: 2018-03-25 22:02:33.479146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446aeac2a500'
down_revision = '5c0f7774b727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dd_summary', sa.Column('iaProgramDeclared', sa.Integer(), nullable=True))
    op.add_column('dd_summary', sa.Column('ihprogramdeclared', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_dd_summary_iaProgramDeclared'), 'dd_summary', ['iaProgramDeclared'], unique=False)
    op.create_index(op.f('ix_dd_summary_ihprogramdeclared'), 'dd_summary', ['ihprogramdeclared'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dd_summary_ihprogramdeclared'), table_name='dd_summary')
    op.drop_index(op.f('ix_dd_summary_iaProgramDeclared'), table_name='dd_summary')
    op.drop_column('dd_summary', 'ihprogramdeclared')
    op.drop_column('dd_summary', 'iaProgramDeclared')
    # ### end Alembic commands ###
